branch-defaults:
  default:
    environment: TwitterHeatMapAssign
global:
  application_name: TwitterHeatMapAssignment1
  default_ec2_keyname: twitter_instance_key
  default_platform: Node.js
  default_region: us-east-1
  profile: null
  sc: null
